=== ercole-io/ercole/schema/license_type.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "required": [
            "id",
            "itemDescription",
            "metric",
            "cost",
            "aliases",
            "option"
        ],
        "properties": {
            "id": {
                "type": "string",
                "minLength": 1
            },
            "itemDescription": {
                "type": "string",
                "minLength": 1
            },
            "metric": {
                "type": "string",
                "minLength": 1
            },
            "cost": {
                "type": "integer"
            },
            "aliases": {
                "type": "array",
                "items": {
                    "type": "string",
                    "minLength": 1
                },
                "uniqueItems": true
            },       
            "option": {
                "type": "boolean"
            }
        }
    }   
}

=== ercole-io/ercole/fixture/test_oracle_database_license_types.json
[
{"id":"A00001","itemDescription":"Oracle Test Item Description","metric":"Test Metric","cost":47500,"aliases":["Test Alias #01","Test Alias #02"],"option":false},
{"id":"A00002","itemDescription":"Oracle Test Item Description","metric":"Test Metric","cost":47501,"aliases":["Test Alias #01","Test Alias #02"],"option":false}
]
